### ISSUE TITLE
Name generation

### ISSUE THREAD

**Issue by mbartelsm** [mbartelsman-dev/dynasties#1]
Name settings are to be pulled from an external, human readable and editable config file

### Config example

```TOML
[given_names.male]
"John" = "1.0"  # Names are weighed
"Jay" = "0.3"  # Probability of being chosen upon random selection
# ...

[given_names.female]
"Dee" = "0.5"
"Jane" = "0.9"
# ...

[family_names]
"Doe" = "0.5"
"Random" = "0.6"
# ...
```
